services:
  api:
    build: .
    container_name: expresscareteam_backend_api
    restart: always
    
  postgres:
    image: postgres:16.9
    container_name: expresscareteam_backend_db
    ports:
      - "${DB_PORT}:5432"
    restart: always
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: redis_expresscareteam
    restart: unless-stopped
    ports:
      - "{REDIS_PORT}:6379"

volumes:
  postgres_data: